
name: AutoPost News

on:
  schedule:
    - cron: "0 7,17 * * *"
  workflow_dispatch:

jobs:
  post-news:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run main.py
      env:
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
      run: python src/main.py
